project:
  type: website
  output-dir: docs


website:
  title: "JesusQuispe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Articles.qmd
      - Articles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

