project:
  type: website
  output-dir: docs


website:
  title: "JesusQuispe"
  navbar:
    left:
      - href: about.qmd
        text: About
      - Articles.qmd

format:
  html:
    theme: Flatly
    css: styles.css
    toc: true

editor: visual

